[build]
  functions = "netlify/functions"
  command = "npm install"

[dev]
  functions = "netlify/functions"
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
