[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

# Redirect API routes to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

# Razorpay routes
[[redirects]]
  from = "/order"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/order/validate"
  to = "/.netlify/functions/app"
  status = 200
